import esbuild from "esbuild";
import process from "process";
import { builtinModules } from "node:module";
import path from "node:path";
import { fileURLToPath } from "node:url";

const banner = "/* Generated by the VaultPilot OS build. See the source repository for editable TypeScript. */";
const production = process.argv[2] === "production";
const projectDir = path.dirname(fileURLToPath(import.meta.url));
const context = await esbuild.context({
  absWorkingDir: projectDir,
  banner: { js: banner },
  entryPoints: [path.join(projectDir, "src", "main.ts")],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtinModules
  ],
  format: "cjs",
  target: "es2021",
  logLevel: "info",
  sourcemap: production ? false : "inline",
  treeShaking: true,
  outfile: path.join(projectDir, "main.js"),
  minify: production
});

if (production) {
  await context.rebuild();
  await context.dispose();
} else {
  await context.watch();
}
